begin;

do $$
begin
  create type public.staff_directory_shift as enum ('day', 'night');
exception
  when duplicate_object then null;
end $$;

alter table public.staff_profiles
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists hire_date date,
  add column if not exists directory_shift public.staff_directory_shift,
  add column if not exists name_aliases text[] not null default '{}'::text[];

alter table public.staff_profiles
  drop constraint if exists staff_profiles_first_name_format,
  drop constraint if exists staff_profiles_last_name_format,
  drop constraint if exists staff_profiles_name_aliases_limit;

alter table public.staff_profiles
  add constraint staff_profiles_first_name_format check (
    first_name is null
    or (first_name = btrim(first_name) and char_length(first_name) between 1 and 80)
  ),
  add constraint staff_profiles_last_name_format check (
    last_name is null
    or (last_name = btrim(last_name) and char_length(last_name) between 1 and 80)
  ),
  add constraint staff_profiles_name_aliases_limit check (cardinality(name_aliases) <= 20);

create index if not exists staff_profiles_directory_seniority_idx
  on public.staff_profiles (
    department_id,
    employment_type,
    directory_shift,
    hire_date,
    last_name,
    first_name
  )
  where is_active = true and operations_role = 'none';

create table if not exists public.staff_directory_seed_conflicts (
  id bigint generated by default as identity primary key,
  department_id uuid not null references public.departments(id) on delete cascade,
  staff_profile_id uuid references public.staff_profiles(id) on delete cascade,
  seed_display_name text not null,
  field_name text not null,
  existing_value text not null,
  incoming_value text not null,
  source_migration text not null,
  detected_at timestamptz not null default now(),
  unique (department_id, seed_display_name, field_name, existing_value, incoming_value)
);

alter table public.staff_directory_seed_conflicts enable row level security;
revoke all on table public.staff_directory_seed_conflicts from public, anon, authenticated;
revoke all on sequence public.staff_directory_seed_conflicts_id_seq from public, anon, authenticated;

create or replace function public.normalize_staff_directory_name(value text)
returns text
language plpgsql
immutable
set search_path = pg_catalog
as $$
declare
  cleaned text;
  comma_parts text[];
begin
  cleaned := pg_catalog.btrim(coalesce(value, ''));
  if pg_catalog.strpos(cleaned, ',') > 0 then
    comma_parts := pg_catalog.string_to_array(cleaned, ',');
    if pg_catalog.cardinality(comma_parts) = 2 then
      cleaned := pg_catalog.btrim(comma_parts[2]) || ' ' || pg_catalog.btrim(comma_parts[1]);
    end if;
  end if;

  return pg_catalog.regexp_replace(
    pg_catalog.lower(pg_catalog.regexp_replace(cleaned, '[^[:alnum:]]+', ' ', 'g')),
    '\s+',
    ' ',
    'g'
  );
end;
$$;

revoke all on function public.normalize_staff_directory_name(text) from public;

create temporary table rt_directory_seed (
  first_name text not null,
  last_name text not null,
  hire_date date not null,
  phone_number text not null,
  employment_type public.staff_employment_type not null,
  directory_shift public.staff_directory_shift not null,
  aliases text[] not null default '{}'::text[],
  primary key (first_name, last_name)
) on commit drop;

insert into rt_directory_seed
  (first_name, last_name, hire_date, phone_number, employment_type, directory_shift, aliases)
values
  ('Mona', 'Ahmed', '2004-06-21', '510-579-0556', 'per_diem', 'day', '{}'),
  ('Victoria', 'Mohsen', '2006-08-07', '510-717-5828', 'per_diem', 'day', array['Victoria Mohseni']),
  ('Leticia', 'Bartolome', '2008-01-14', '510-766-9936', 'per_diem', 'day', '{}'),
  ('Carlos', 'Ruvalcaba', '2011-07-11', '408-401-7965', 'per_diem', 'night', '{}'),
  ('Mai', 'Vu', '2018-10-03', '408-334-2147', 'per_diem', 'day', '{}'),
  ('John', 'Roberts', '2019-05-06', '925-683-7228', 'per_diem', 'day', array['Marshall Roberts', 'John Roberts (Marshall)']),
  ('Solyanna', 'Beyene', '2020-05-14', '773-328-9734', 'per_diem', 'night', '{}'),
  ('Regie', 'De Jesus', '2020-05-14', '510-304-2547', 'per_diem', 'night', array['Reggie De Jesus', 'Regie DeJesus', 'Reggie DeJesus']),
  ('Peter', 'Van Dal', '2021-12-06', '818-427-2998', 'per_diem', 'day', array['Pete Van Dal', 'Peter Van Dal (Pete)', 'Peter Vandal', 'Pete Vandal']),
  ('Aisha', 'Bahrami', '2022-08-04', '510-925-5251', 'per_diem', 'day', '{}'),
  ('Nina', 'Ksovreli', '2023-02-01', '732-318-5086', 'per_diem', 'day', '{}'),
  ('Harjot', 'Kaur', '2023-02-06', '805-815-5178', 'per_diem', 'day', array['Joy Kaur', 'Harjot Kaur (Joy)']),
  ('Kae', 'Alameda', '2023-04-27', '408-828-3590', 'per_diem', 'night', '{}'),
  ('Jemin', 'Perenia', '2023-05-02', '832-466-2726', 'per_diem', 'day', array['Aby Perenia', 'Jemin Perenia (Aby)']),
  ('Andrea', 'Watkins', '2023-06-01', '408-891-0469', 'per_diem', 'day', '{}'),
  ('Kaitlyn', 'Trivisonno', '2023-06-22', '916-886-1490', 'per_diem', 'night', '{}'),
  ('Erica', 'Collins', '2024-06-03', '650-222-6650', 'per_diem', 'night', '{}'),
  ('Catherine', 'Morgan', '2024-06-11', '408-250-5174', 'per_diem', 'night', '{}'),
  ('Tom', 'Macasaet', '2025-02-17', '510-714-6891', 'per_diem', 'day', '{}'),
  ('Elizabeth', 'Ricker', '1985-10-18', '510-304-3848', 'full_time', 'day', array['Beth Ricker', 'Elizabeth Ricker (Beth)']),
  ('Raul', 'Rodriquez', '1993-12-06', '510-427-1358', 'full_time', 'day', array['Raul Rodriguez']),
  ('Anna', 'Vaysburg', '1994-07-11', '925-915-0044', 'full_time', 'day', '{}'),
  ('Rudy', 'Teodosio', '1994-08-08', '510-453-1868', 'full_time', 'day', '{}'),
  ('Allan Dale', 'Timbang', '1995-06-12', '510-304-4918', 'full_time', 'day', array['Allan Timbang']),
  ('David', 'Winters', '1996-03-18', '408-315-2951', 'full_time', 'day', '{}'),
  ('Emmanuel', 'Rivera', '1996-11-25', '510-673-3998', 'full_time', 'day', '{}'),
  ('Sherry', 'Harrington', '1999-09-27', '925-487-5288', 'full_time', 'day', '{}'),
  ('Kinty', 'Khera', '2001-10-01', '510-501-6630', 'full_time', 'day', array['Pawanjit Khera', 'Pawanjit Khera (Kinty)']),
  ('Diana', 'Oblitas', '2001-11-14', '510-999-2012', 'full_time', 'day', '{}'),
  ('Heather', 'Heath', '2002-03-11', '510-414-3463', 'full_time', 'day', '{}'),
  ('Cecilia', 'Martinez', '2002-05-15', '408-425-9900', 'full_time', 'day', '{}'),
  ('Danielle', 'Rigdon', '2008-04-21', '510-701-0228', 'full_time', 'day', '{}'),
  ('Tom', 'Nguyen', '2010-03-15', '714-655-3007', 'full_time', 'day', '{}'),
  ('Maggie', 'Meng', '2010-06-21', '510-857-3336', 'full_time', 'day', array['Yiqin Meng', 'Yiqin Meng (Maggie)']),
  ('Bei', 'Yi', '2015-01-24', '510-386-3856', 'full_time', 'day', '{}'),
  ('Win', 'Hlaing', '2016-02-23', '510-396-5490', 'full_time', 'day', '{}'),
  ('Beletu', 'Shoge', '2016-05-12', '925-597-3465', 'full_time', 'day', '{}'),
  ('Gina', 'Martinez', '2016-09-23', '510-304-6579', 'full_time', 'day', '{}'),
  ('Katryna', 'Vuong', '2019-05-03', '408-421-5624', 'full_time', 'day', '{}'),
  ('Jonathan', 'Burdick', '2022-03-03', '510-676-7799', 'full_time', 'day', '{}'),
  ('Ruth', 'Deguzman', '1998-05-13', '510-366-7446', 'full_time', 'night', '{}'),
  ('Joann', 'Devera', '1999-12-16', '510-396-7211', 'full_time', 'night', '{}'),
  ('Meldy', 'Pak', '2002-02-19', '510-862-7679', 'full_time', 'night', '{}'),
  ('Victor', 'Davis', '2003-12-01', '775-232-1588', 'full_time', 'night', '{}'),
  ('Pablo', 'Baluyut', '2009-04-20', '408-221-8468', 'full_time', 'night', '{}'),
  ('Jean', 'Rodrillo', '2010-09-20', '510-402-3692', 'full_time', 'night', '{}'),
  ('My-Quyen', 'Giang', '2010-09-20', '408-646-4471', 'full_time', 'night', '{}'),
  ('Anthony', 'Alix', '2013-03-11', '510-938-2374', 'full_time', 'night', '{}'),
  ('Renae', 'Waldschmidt', '2017-12-19', '510-673-7819', 'full_time', 'night', '{}'),
  ('Carl', 'Lin', '2019-05-09', '415-971-2773', 'full_time', 'night', '{}'),
  ('Yu', 'Lin', '2019-05-09', '502-457-2562', 'full_time', 'night', '{}'),
  ('Eduardo', 'Gonzalez', '2019-06-28', '510-499-0873', 'full_time', 'night', '{}'),
  ('Gene', 'Benoza', '2019-09-16', '510-598-7681', 'full_time', 'night', '{}'),
  ('Vanessa', 'Osgood', '2019-09-16', '925-337-3510', 'full_time', 'night', '{}'),
  ('Anthony', 'Lanchinebre', '2020-05-14', '510-861-5221', 'full_time', 'night', '{}'),
  ('Stefanie', 'Ortiz', '2022-09-23', '510-857-6363', 'full_time', 'night', array['Stephanie Ortiz']);

create temporary table rt_directory_resolution on commit drop as
select
  department.id as department_id,
  seed.*,
  matches.staff_ids,
  coalesce(pg_catalog.cardinality(matches.staff_ids), 0) as match_count
from public.departments department
cross join rt_directory_seed seed
left join lateral (
  select pg_catalog.array_agg(profile.id order by profile.id) as staff_ids
  from public.staff_profiles profile
  where profile.department_id = department.id
    and public.normalize_staff_directory_name(profile.display_name) = any (
      select public.normalize_staff_directory_name(candidate.name)
      from pg_catalog.unnest(
        array[seed.first_name || ' ' || seed.last_name] || seed.aliases
      ) as candidate(name)
    )
) matches on true;

insert into public.staff_directory_seed_conflicts (
  department_id,
  staff_profile_id,
  seed_display_name,
  field_name,
  existing_value,
  incoming_value,
  source_migration
)
select
  resolution.department_id,
  null,
  resolution.first_name || ' ' || resolution.last_name,
  'identity',
  pg_catalog.array_to_string(resolution.staff_ids, ', '),
  'Exactly one existing staff profile',
  '202608150003_lead_schedule_employee_directory'
from rt_directory_resolution resolution
where resolution.match_count > 1
on conflict do nothing;

with insert_candidates as (
  select
    resolution.*,
    public.generated_staff_username_base(resolution.first_name || ' ' || resolution.last_name) as base_username,
    row_number() over (
      partition by public.generated_staff_username_base(resolution.first_name || ' ' || resolution.last_name)
      order by resolution.department_id, resolution.last_name, resolution.first_name
    ) as username_rank
  from rt_directory_resolution resolution
  where resolution.match_count = 0
), resolved_usernames as (
  select
    candidate.*,
    available.username
  from insert_candidates candidate
  cross join lateral (
    select username_option.username
    from (
      select
        sequence.value,
        case
          when sequence.value = 0 then candidate.base_username
          else candidate.base_username || (sequence.value + 1)::text
        end as username
      from pg_catalog.generate_series(0, 999) as sequence(value)
    ) username_option
    where not exists (
      select 1
      from public.staff_profiles existing
      where existing.username_normalized = public.normalize_username(username_option.username)
    )
    order by username_option.value
    offset (candidate.username_rank - 1)
    limit 1
  ) available
)
insert into public.staff_profiles (
  department_id,
  display_name,
  first_name,
  last_name,
  hire_date,
  phone_number,
  employment_type,
  home_assignment,
  directory_shift,
  name_aliases,
  username,
  username_normalized,
  operations_role,
  is_active
)
select
  resolution.department_id,
  resolution.first_name || ' ' || resolution.last_name,
  resolution.first_name,
  resolution.last_name,
  resolution.hire_date,
  resolution.phone_number,
  resolution.employment_type,
  case resolution.directory_shift
    when 'night' then 'night_shift'::public.staff_home_assignment
    else 'day_shift'::public.staff_home_assignment
  end,
  resolution.directory_shift,
  resolution.aliases,
  resolution.username,
  public.normalize_username(resolution.username),
  'none',
  true
from resolved_usernames resolution
on conflict (department_id, display_name) do nothing;

truncate rt_directory_resolution;

insert into rt_directory_resolution
select
  department.id as department_id,
  seed.*,
  matches.staff_ids,
  coalesce(pg_catalog.cardinality(matches.staff_ids), 0) as match_count
from public.departments department
cross join rt_directory_seed seed
left join lateral (
  select pg_catalog.array_agg(profile.id order by profile.id) as staff_ids
  from public.staff_profiles profile
  where profile.department_id = department.id
    and public.normalize_staff_directory_name(profile.display_name) = any (
      select public.normalize_staff_directory_name(candidate.name)
      from pg_catalog.unnest(
        array[seed.first_name || ' ' || seed.last_name] || seed.aliases
      ) as candidate(name)
    )
) matches on true;

insert into public.staff_directory_seed_conflicts (
  department_id,
  staff_profile_id,
  seed_display_name,
  field_name,
  existing_value,
  incoming_value,
  source_migration
)
select
  resolution.department_id,
  resolution.staff_ids[1],
  resolution.first_name || ' ' || resolution.last_name,
  conflict.field_name,
  conflict.existing_value,
  conflict.incoming_value,
  '202608150003_lead_schedule_employee_directory'
from rt_directory_resolution resolution
join public.staff_profiles profile on profile.id = resolution.staff_ids[1]
cross join lateral (
  values
    ('first_name', profile.first_name, resolution.first_name),
    ('last_name', profile.last_name, resolution.last_name),
    ('hire_date', profile.hire_date::text, resolution.hire_date::text),
    ('phone_number', profile.phone_number, resolution.phone_number),
    ('employment_type', profile.employment_type::text, resolution.employment_type::text),
    ('directory_shift', profile.directory_shift::text, resolution.directory_shift::text)
) as conflict(field_name, existing_value, incoming_value)
where resolution.match_count = 1
  and conflict.existing_value is not null
  and conflict.existing_value <> conflict.incoming_value
on conflict do nothing;

update public.staff_profiles profile
set
  first_name = coalesce(profile.first_name, resolution.first_name),
  last_name = coalesce(profile.last_name, resolution.last_name),
  hire_date = coalesce(profile.hire_date, resolution.hire_date),
  phone_number = coalesce(profile.phone_number, resolution.phone_number),
  employment_type = case
    when resolution.first_name = 'Renae' and resolution.last_name = 'Waldschmidt'
      then resolution.employment_type
    else profile.employment_type
  end,
  directory_shift = coalesce(profile.directory_shift, resolution.directory_shift),
  name_aliases = array(
    select distinct alias_value
    from pg_catalog.unnest(
      profile.name_aliases || resolution.aliases
    ) as alias_value
    where pg_catalog.btrim(alias_value) <> ''
    order by alias_value
  )
from rt_directory_resolution resolution
where resolution.match_count = 1
  and profile.id = resolution.staff_ids[1];

commit;
